[package]
name = "ekubo_swap_helper"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
starkware_utils.workspace = true
ekubo.workspace = true
privacy = { path = "../privacy" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
starkware_utils_testing.workspace = true

[features]
test_utils = []

[lib]

[[test]]
name = "ekubo_swap_helper_unittest"
build-external-contracts = [
    "starkware_utils::erc20::erc20_mocks::DualCaseERC20Mock",
    "ekubo_swap_helper::test_utils_contracts::mock_ekubo_amm::MockEkuboAMM",
]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
