use core::num::traits::Zero;
use privacy::objects::EncChannelInfo;
use privacy::utils::constants::{OPEN_NOTE_SALT, TWO_POW_120};
use privacy::{errors, events};
use starknet::ContractAddress;

pub(crate) trait InputValidation<T> {
    fn assert_valid(self: T);
}

/// Input for the `SetViewingKey` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct SetViewingKeyInput {
    /// A random value used to encrypt the private key for the auditor. Generated by the user.
    pub random: felt252,
}

pub(crate) impl SetViewingKeyInputValid of InputValidation<SetViewingKeyInput> {
    fn assert_valid(self: SetViewingKeyInput) {
        let SetViewingKeyInput { random } = self;
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `OpenChannel` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenChannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The channel index within the sender's outgoing channels.
    pub index: usize,
    /// A random value used to encrypt the channel info for the recipient. Generated by the sender.
    pub random: felt252,
    /// A salt generated by the sender. Used to guarantee one-time key usage for the encrypted
    /// outgoing channel info.
    pub salt: felt252,
}

pub(crate) impl OpenChannelInputValid of InputValidation<OpenChannelInput> {
    fn assert_valid(self: OpenChannelInput) {
        let OpenChannelInput { recipient_addr, index: _, random, salt } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
    }
}

/// Input for the `OpenSubchannel` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same subchannel id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenSubchannelInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The channel key of the subchannel.
    pub channel_key: felt252,
    /// The index of the subchannel within the channel.
    pub index: usize,
    /// The token of the subchannel.
    pub token: ContractAddress,
    /// A salt used to encrypt the subchannel token. Generated by the sender.
    pub salt: felt252,
}

pub(crate) impl OpenSubchannelInputValid of InputValidation<OpenSubchannelInput> {
    fn assert_valid(self: OpenSubchannelInput) {
        let OpenSubchannelInput {
            recipient_addr, recipient_public_key, channel_key: _, index: _, token, salt,
        } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
    }
}

/// Input for the `CreateEncNote` action.
///
/// Includes a salt to guarantee one-time key usage, preventing privacy-related data leakage
/// if a transaction is reverted and the same note id is reused.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateEncNoteInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount the note represents.
    pub amount: u128,
    /// The index of the note within the channel.
    pub index: usize,
    /// A salt generated by the sender to guarantee one-time key usage.
    /// Must be 120 bits and > OPEN_NOTE_SALT (=1).
    /// (`salt = 1` is reserved for the open (non-encrypted) note, and `salt = 0` indicates the note
    /// does not exist.)
    pub salt: u128,
}

pub(crate) impl CreateEncNoteInputValid of InputValidation<CreateEncNoteInput> {
    fn assert_valid(self: CreateEncNoteInput) {
        let CreateEncNoteInput {
            recipient_addr, recipient_public_key, token, amount: _, index: _, salt,
        } = self;
        // Zero `amount` is allowed to enable note creation on reverted transaction indexes,
        // preventing data leakage from index reuse after a revert.
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(salt.is_non_zero(), errors::ZERO_SALT);
        assert(salt > OPEN_NOTE_SALT, errors::SALT_TOO_SMALL);
        assert(salt < TWO_POW_120, errors::SALT_EXCEEDS_120_BITS);
    }
}

/// Input for the `CreateOpenNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct CreateOpenNoteInput {
    /// The recipient's address.
    pub recipient_addr: ContractAddress,
    /// The recipient's public key.
    pub recipient_public_key: felt252,
    /// The token's address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    pub index: usize,
    /// A random value used to encrypt the recipient address for the auditor. Generated by the
    /// sender.
    pub random: felt252,
}

pub(crate) impl CreateOpenNoteInputValid of InputValidation<CreateOpenNoteInput> {
    fn assert_valid(self: CreateOpenNoteInput) {
        let CreateOpenNoteInput {
            recipient_addr, recipient_public_key, token, index: _, random,
        } = self;
        assert(recipient_addr.is_non_zero(), errors::ZERO_RECIPIENT_ADDR);
        assert(recipient_public_key.is_non_zero(), errors::ZERO_RECIPIENT_PUBLIC_KEY);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `Deposit` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct DepositInput {
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to deposit.
    pub amount: u128,
}

pub(crate) impl DepositInputValid of InputValidation<DepositInput> {
    fn assert_valid(self: DepositInput) {
        let DepositInput { token, amount } = self;
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(amount.is_non_zero(), errors::ZERO_AMOUNT);
    }
}

/// Input for the `UseNote` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct UseNoteInput {
    /// The channel key of the note's channel.
    pub channel_key: felt252,
    /// The note's token address.
    pub token: ContractAddress,
    /// The index of the note within the channel.
    pub index: usize,
}

pub(crate) impl UseNoteInputValid of InputValidation<UseNoteInput> {
    fn assert_valid(self: UseNoteInput) {
        let UseNoteInput { channel_key: _, token, index: _ } = self;
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
    }
}

/// Input for the `Withdraw` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WithdrawInput {
    /// The address to withdraw to.
    pub to_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to withdraw.
    pub amount: u128,
    /// A random value used to encrypt the user address for the auditor. Generated by the user.
    pub random: felt252,
}

pub(crate) impl WithdrawInputValid of InputValidation<WithdrawInput> {
    fn assert_valid(self: WithdrawInput) {
        let WithdrawInput { to_addr, token, amount, random } = self;
        assert(to_addr.is_non_zero(), errors::ZERO_TO_ADDR);
        assert(token.is_non_zero(), errors::ZERO_TOKEN);
        assert(amount.is_non_zero(), errors::ZERO_AMOUNT);
        assert(random.is_non_zero(), errors::ZERO_RANDOM);
    }
}

/// Input for the `InvokeExternal` client action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct InvokeExternalInput {
    /// The target contract address to invoke.
    pub contract_address: ContractAddress,
    /// The calldata to pass to the target contract.
    pub calldata: Span<felt252>,
}

pub(crate) impl InvokeExternalInputValid of InputValidation<InvokeExternalInput> {
    fn assert_valid(self: InvokeExternalInput) {
        let InvokeExternalInput { contract_address, calldata: _ } = self;
        assert(contract_address.is_non_zero(), errors::ZERO_CONTRACT_ADDRESS);
    }
}

/// An action to be executed by the client.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ClientAction {
    /// Register a user with a viewing key. The key is immutable once set (enforced via WriteOnce).
    SetViewingKey: SetViewingKeyInput,
    /// Open a new channel from the user to a recipient.
    OpenChannel: OpenChannelInput,
    /// Open a new subchannel from the user to a recipient.
    OpenSubchannel: OpenSubchannelInput,
    /// Creates a new encrypted note with a specified amount.
    CreateEncNote: CreateEncNoteInput,
    /// Creates a new open note (unencrypted, zero-value note to be deposited to by a server
    /// action).
    /// Open notes enable interactions where the final amount is determined at execution time,
    /// such as AMM swaps or receiving funds directly through bridge transfers.
    CreateOpenNote: CreateOpenNoteInput,
    /// Deposit funds into the contract.
    Deposit: DepositInput,
    /// Uses up a note (creates a nullifier for it).
    UseNote: UseNoteInput,
    /// Withdraw funds from the contract.
    Withdraw: WithdrawInput,
    /// Invokes an external contract: forwards the contract address and calldata as a server-side
    /// Invoke action.
    InvokeExternal: InvokeExternalInput,
}

#[generate_trait]
pub(crate) impl ClientActionImpl of ClientActionTrait {
    const ACCOUNT_PHASE: u8 = 0;
    const CHANNEL_PHASE: u8 = 1;
    const SUBCHANNEL_PHASE: u8 = 2;
    const DEPOSIT_PHASE: u8 = 3;
    const USE_NOTES_PHASE: u8 = 4;
    const CREATE_NOTES_PHASE: u8 = 5;
    const WITHDRAW_PHASE: u8 = 6;
    const INVOKE_PHASE: u8 = 7;

    /// Returns the phase associated with this action.
    fn phase(self: @ClientAction) -> u8 {
        match self {
            ClientAction::SetViewingKey(_) => Self::ACCOUNT_PHASE,
            ClientAction::OpenChannel(_) => Self::CHANNEL_PHASE,
            ClientAction::OpenSubchannel(_) => Self::SUBCHANNEL_PHASE,
            ClientAction::Deposit(_) => Self::DEPOSIT_PHASE,
            ClientAction::CreateEncNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::CreateOpenNote(_) => Self::CREATE_NOTES_PHASE,
            ClientAction::UseNote(_) => Self::USE_NOTES_PHASE,
            ClientAction::Withdraw(_) => Self::WITHDRAW_PHASE,
            ClientAction::InvokeExternal(_) => Self::INVOKE_PHASE,
        }
    }

    /// Asserts action_phase >= curr_phase (ACTIONS_OUT_OF_ORDER) and update `curr_phase` to the
    /// phase to advance to.
    /// InvokeExternal is only allowed once per Tx.
    fn assert_and_advance_phase(self: @ClientAction, ref curr_phase: u8) {
        let action_phase = self.phase();
        assert(action_phase >= curr_phase, errors::ACTIONS_OUT_OF_ORDER);
        curr_phase =
            if action_phase == Self::INVOKE_PHASE {
                action_phase + 1
            } else {
                action_phase
            }
    }
}

/// Input for the `WriteOnce` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct WriteOnceInput {
    /// The (base) storage address to write to.
    pub storage_address: felt252,
    /// The value to write, stored sequentially starting at the given storage address.
    pub value: Span<felt252>,
}

/// Input for the `Append` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct AppendInput {
    /// The recipient's address, which is the key of the map in storage.
    pub recipient_addr: ContractAddress,
    /// The channel info to append.
    pub enc_channel_info: EncChannelInfo,
}

/// Input for the `TransferFrom` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferFromInput {
    /// The address to transfer from.
    pub from_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `TransferTo` action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct TransferToInput {
    /// The address to transfer to.
    pub to_addr: ContractAddress,
    /// The token's address.
    pub token: ContractAddress,
    /// The amount to transfer.
    pub amount: u128,
}

/// Input for the `Invoke` server action.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct InvokeInput {
    /// The target contract address to invoke.
    pub contract_address: ContractAddress,
    /// The calldata to pass to the target contract.
    pub calldata: Span<felt252>,
}

/// An action to be executed by the server.
#[derive(Serde, Copy, Drop, Debug, PartialEq)]
pub enum ServerAction {
    /// Verify that a storage value is zero/empty and then write to it.
    WriteOnce: WriteOnceInput,
    /// Append a `EncChannelInfo` value to `recipient_addr`'s vector in storage.
    Append: AppendInput,
    /// Transfer tokens from a user to the contract (ERC20 transfer_from).
    TransferFrom: TransferFromInput,
    /// Transfer tokens from the contract to a recipient (ERC20 transfer).
    TransferTo: TransferToInput,
    /// Emit [`ViewingKeySet`](privacy::events::ViewingKeySet) event.
    EmitViewingKeySet: events::ViewingKeySet,
    /// Emit [`Withdrawal`](privacy::events::Withdrawal) event.
    EmitWithdrawal: events::Withdrawal,
    /// Emit [`Deposit`](privacy::events::Deposit) event.
    EmitDeposit: events::Deposit,
    /// Emit [`OpenNoteCreated`](privacy::events::OpenNoteCreated) event.
    EmitOpenNoteCreated: events::OpenNoteCreated,
    /// Emit [`EncNoteCreated`](privacy::events::EncNoteCreated) event.
    EmitEncNoteCreated: events::EncNoteCreated,
    /// Emit [`NoteUsed`](privacy::events::NoteUsed) event.
    EmitNoteUsed: events::NoteUsed,
    /// Invoke an external contract via the
    /// [`INVOKE_SELECTOR`](privacy::utils::constants::INVOKE_SELECTOR) selector.
    Invoke: InvokeInput,
}
