use core::dict::{Felt252Dict, Felt252DictEntryTrait, SquashedFelt252Dict, SquashedFelt252DictTrait};
use core::num::traits::{CheckedSub, Zero};
use privacy::errors;
use starknet::ContractAddress;

pub(crate) type TokenBalances = Felt252Dict<u128>;
pub(crate) type SquashedTokenBalances = SquashedFelt252Dict<u128>;

#[generate_trait]
pub(crate) impl TokenBalancesImpl of TokenBalancesTrait {
    fn add_balance(ref self: TokenBalances, token: ContractAddress, amount: u128) {
        let (entry, current_balance) = self.entry(key: token.into());
        self = entry.finalize(new_value: current_balance + amount);
    }
    fn subtract_balance(ref self: TokenBalances, token: ContractAddress, amount: u128) {
        let (entry, current_balance) = self.entry(key: token.into());
        let new_value = current_balance
            .checked_sub(amount)
            .expect(errors::NEGATIVE_INTERMEDIATE_BALANCE);
        self = entry.finalize(:new_value);
    }
    fn assert_valid(self: SquashedTokenBalances) {
        for (_token, _, balance) in self.into_entries() {
            assert(balance.is_zero(), errors::FINAL_BALANCE_MUST_BE_ZERO);
        }
    }
}

/// Ciphertext for an ECDH-based encryption of channel data.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncChannelInfo {
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the recipient to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted channel key.
    /// `enc_channel_key = h(CHANNEL_KEY_TAG, rK.x) + channel_key`
    pub enc_channel_key: felt252,
    /// Encrypted sender address.
    /// `enc_sender_addr = h(SENDER_ADDR_TAG, rK.x) + sender_addr`
    pub enc_sender_addr: felt252,
}

/// Ciphertext for an ECDH-based encryption of private key.
/// Used for the auditor to be able to decrypt the private key.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub(crate) struct EncPrivateKey {
    /// Auditor public key used for encryption.
    pub auditor_public_key: felt252,
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the auditor to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted private key.
    /// `enc_private_key = h(ENC_PRIVATE_KEY_TAG, rK.x) + private_key`
    pub enc_private_key: felt252,
}

/// An encrypted subchannel info, to be written to storage.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncSubchannelInfo {
    /// A salt generated by the sender. Used to guarantee one-time key usage.
    pub salt: felt252,
    /// The encrypted token.
    /// `enc_token = h(ENC_TOKEN_TAG, channel_key, index, 0, salt) + token`.
    pub enc_token: felt252,
}

/// Ciphertext for an ECDH-based encryption of user address.
/// Used for the auditor to be able to decrypt the user address when withdrawing.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub(crate) struct EncUserAddr {
    /// Auditor public key used for encryption.
    pub auditor_public_key: felt252,
    /// Ephemeral ECDH public key x-coordinate (rG.x). Used by the auditor to derive rK.
    pub ephemeral_pubkey: felt252,
    /// Encrypted user address.
    /// `enc_user_addr = h(ENC_USER_ADDR_TAG, rK.x) + user_addr`
    pub enc_user_addr: felt252,
}

/// An encrypted outgoing channel info, to be written to storage.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct EncOutgoingChannelInfo {
    /// A salt generated by the sender. Used to guarantee one-time key usage.
    pub salt: felt252,
    /// The encrypted recipient address.
    /// `enc_recipient_addr = h(ENC_RECIPIENT_ADDR_TAG, sender_addr, sender_private_key, index, 0,
    /// salt) + recipient_addr`.
    pub enc_recipient_addr: felt252,
}

/// A note containing encrypted value and token information.
#[derive(Drop, Serde, starknet::Store, PartialEq, Debug, Copy)]
pub struct Note {
    /// The packed value of the note `(salt, amount)`:
    /// - For open notes: salt = OPEN_NOTE_SALT (=1), amount = zero (awaiting deposit) / non-zero
    /// amount if already deposited.
    /// - For encrypted notes: salt > OPEN_NOTE_SALT (>=2), amount = encrypted amount =
    /// `(h(ENC_AMOUNT_TAG, channel_key, token, index, 0, salt) + amount) % 2^128`.
    pub packed_value: felt252,
    /// The token address of the note (zero for encrypted notes).
    pub token: ContractAddress,
}

/// Input for depositing to an open note (returned by invoked contract).
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub struct OpenNoteDeposit {
    /// The identifier of the open note to deposit to.
    pub note_id: felt252,
    /// The ERC20 token contract to deposit.
    pub token: ContractAddress,
    /// The amount of tokens to deposit.
    pub amount: u128,
}
