[package]
name = "privacy"
readme = "README.md"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
starkware_utils.workspace = true

[dev-dependencies]
assert_macros.workspace = true
ekubo.workspace = true
ekubo_swap_helper = { path = "../ekubo_swap_helper", features = ["test_utils"] }
snforge_std.workspace = true
starkware_utils_testing.workspace = true
vesu_lending_helper = { path = "../vesu_lending_helper", features = ["test_utils"] }

[[test]]
name = "privacy_unittest"
build-external-contracts = [
    "starkware_utils::erc20::erc20_mocks::DualCaseERC20Mock",
    "ekubo_swap_helper::ekubo_swap_helper::EkuboSwapHelper",
    "ekubo_swap_helper::test_utils_contracts::mock_ekubo_amm::MockEkuboAMM",
    "vesu_lending_helper::vesu_lending_helper::VesuLendingHelper",
    "vesu_lending_helper::test_utils_contracts::mock_vesu_vault::MockVesuVault",
    "vesu_lending_helper::test_utils_contracts::mock_vesu_vault::MockVesuVaultNoop",
    "vesu_lending_helper::test_utils_contracts::mock_vesu_vault::MockVesuVaultOverflow",
]

[features]
test_contracts = []

[scripts]
test = "snforge test"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[profile.release.cairo]
inlining-strategy = 250