[workspace]
members = [
    "packages/ekubo_swap_helper",
    "packages/privacy",
    "packages/vesu_lending_helper",
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.17.0-rc.4"
snforge_std = { version = "0.55.0+nightly-2026-02-20", registry = "https://scarbs.dev/" }
assert_macros = "2.17.0-rc.4"
# TODO: once openzeppelin upgrades to Cairo >=2.17, remove all SCARB_IGNORE_CAIRO_VERSION
# flags from CI workflows and sdk/package.json scripts
openzeppelin = "3.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/starknet-contracts", rev = "8b4de8b5701d10b101c06b786740bf45b6cf15cb" }
starkware_utils = { git ="https://github.com/starkware-libs/starkware-starknet-utils", rev="0e12df09afe29f59a877a5b04801fedd8b31c50d" }
starkware_utils_testing = { git="https://github.com/starkware-libs/starkware-starknet-utils", rev="0e12df09afe29f59a877a5b04801fedd8b31c50d" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[[target.starknet-contract]]
casm = true

[[test]]
name = "unittest"

[profile.release.cairo]
inlining-strategy = 250
